export type ProductItemT = {
	id: string;
	material: string;
	brand: string;
	name: string;
	imageUrl: string;
};

export const mockData = [
	{
		title: 'PODŁOGI',
		items: [
			{
				id: 'al57at7',
				material: 'DREWNO',
				brand: 'Fabri',
				name: 'Fabri - 1',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'dvi0wg4',
				material: 'DREWNO',
				brand: 'Fabri',
				name: 'Fabri - 2',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '9w64pm5',
				material: 'DREWNO',
				brand: 'Fabri',
				name: 'Fabri - 3',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '5jrb71j',
				material: 'DREWNO',
				brand: 'Fabri',
				name: 'Fabri - 4',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '38d16lj',
				material: 'DREWNO',
				brand: 'Fabri',
				name: 'Fabri - 5',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '58dfyt8',
				material: 'DREWNO',
				brand: 'Fabri',
				name: 'Fabri - 6',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'zb7dih1',
				material: 'DREWNO',
				brand: 'Fabri',
				name: 'Fabri - 7',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'fq5rpm7',
				material: 'DREWNO',
				brand: 'Fabri',
				name: 'Fabri - 8',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '65zvuje',
				material: 'DREWNO',
				brand: 'Fabri',
				name: 'Fabri - 9',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'ze38x8x',
				material: 'DREWNO',
				brand: 'Fabri',
				name: 'Fabri - 10',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '5173ngh',
				material: 'DREWNO',
				brand: 'Fabri',
				name: 'Fabri - 11',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'ii9hrnw',
				material: 'DREWNO',
				brand: 'Fabri',
				name: 'Fabri - 12',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '09lpd2o',
				material: 'DREWNO',
				brand: 'Fabri',
				name: 'Fabri - 13',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '1r0yu7j',
				material: 'DREWNO',
				brand: 'Fabri',
				name: 'Fabri - 14',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'guhdep9',
				material: 'DREWNO',
				brand: 'Fabri',
				name: 'Fabri - 15',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '5roqg2y',
				material: 'DREWNO',
				brand: 'Fabri',
				name: 'Fabri - 16',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'n1w7h7y',
				material: 'DREWNO',
				brand: 'Fabri',
				name: 'Fabri - 17',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'nvy9udl',
				material: 'DREWNO',
				brand: 'Fabri',
				name: 'Fabri - 18',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'hfz60v2',
				material: 'DREWNO',
				brand: 'Fabri',
				name: 'Fabri - 19',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'o0e1sx5',
				material: 'DREWNO',
				brand: 'Fabri',
				name: 'Fabri - 20',
				imageUrl: 'https://via.placeholder.com/150',
			},
		],
	},
	{
		title: 'TKANINY',
		items: [
			{
				id: '8ve2uft',
				material: 'TKANINA OBICIOWA',
				brand: 'Toptextil',
				name: 'Wzór - 1',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'd50f669',
				material: 'TKANINA OBICIOWA',
				brand: 'Toptextil',
				name: 'Wzór - 2',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 's560iaj',
				material: 'TKANINA OBICIOWA',
				brand: 'Toptextil',
				name: 'Wzór - 3',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '6pnez1h',
				material: 'TKANINA OBICIOWA',
				brand: 'Toptextil',
				name: 'Wzór - 4',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'o9qdtj8',
				material: 'TKANINA OBICIOWA',
				brand: 'Toptextil',
				name: 'Wzór - 5',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '5j7dix2',
				material: 'TKANINA OBICIOWA',
				brand: 'Toptextil',
				name: 'Wzór - 6',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'ey69u9n',
				material: 'TKANINA OBICIOWA',
				brand: 'Toptextil',
				name: 'Wzór - 7',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '0510t73',
				material: 'TKANINA OBICIOWA',
				brand: 'Toptextil',
				name: 'Wzór - 8',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'n06vci0',
				material: 'TKANINA OBICIOWA',
				brand: 'Toptextil',
				name: 'Wzór - 9',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '8c0gnme',
				material: 'TKANINA OBICIOWA',
				brand: 'Toptextil',
				name: 'Wzór - 10',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'dxm70uu',
				material: 'TKANINA OBICIOWA',
				brand: 'Toptextil',
				name: 'Wzór - 11',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'zjhj6w0',
				material: 'TKANINA OBICIOWA',
				brand: 'Toptextil',
				name: 'Wzór - 12',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'chl1ixz',
				material: 'TKANINA OBICIOWA',
				brand: 'Toptextil',
				name: 'Wzór - 13',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'v249h9q',
				material: 'TKANINA OBICIOWA',
				brand: 'Toptextil',
				name: 'Wzór - 14',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '41de7p0',
				material: 'TKANINA OBICIOWA',
				brand: 'Toptextil',
				name: 'Wzór - 15',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'rhfivr9',
				material: 'TKANINA OBICIOWA',
				brand: 'Toptextil',
				name: 'Wzór - 16',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'lgk5bta',
				material: 'TKANINA OBICIOWA',
				brand: 'Toptextil',
				name: 'Wzór - 17',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'ur7bj50',
				material: 'TKANINA OBICIOWA',
				brand: 'Toptextil',
				name: 'Wzór - 18',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'k31k1wo',
				material: 'TKANINA OBICIOWA',
				brand: 'Toptextil',
				name: 'Wzór - 19',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'mossj46',
				material: 'TKANINA OBICIOWA',
				brand: 'Toptextil',
				name: 'Wzór - 20',
				imageUrl: 'https://via.placeholder.com/150',
			},
		],
	},
	{
		title: 'PŁYTKI',
		items: [
			{
				id: 'hq10hjv',
				material: 'GRES',
				brand: 'Opoczno',
				name: 'Terrazzo Stone - 1',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'qdoduke',
				material: 'GRES',
				brand: 'Opoczno',
				name: 'Terrazzo Stone - 2',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'jhaprny',
				material: 'GRES',
				brand: 'Opoczno',
				name: 'Terrazzo Stone - 3',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'kubjw74',
				material: 'GRES',
				brand: 'Opoczno',
				name: 'Terrazzo Stone - 4',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'tgijchv',
				material: 'GRES',
				brand: 'Opoczno',
				name: 'Terrazzo Stone - 5',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'k4q6wv8',
				material: 'GRES',
				brand: 'Opoczno',
				name: 'Terrazzo Stone - 6',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '86zovip',
				material: 'GRES',
				brand: 'Opoczno',
				name: 'Terrazzo Stone - 7',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'mxd82w7',
				material: 'GLAZURA',
				brand: 'Cersanit',
				name: 'Marble Viola - 1',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'fgxj9xi',
				material: 'GLAZURA',
				brand: 'Cersanit',
				name: 'Marble Viola - 2',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'hcexgth',
				material: 'GLAZURA',
				brand: 'Cersanit',
				name: 'Marble Viola - 3',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'e6nex5h',
				material: 'GLAZURA',
				brand: 'Cersanit',
				name: 'Marble Viola - 4',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '9n0yj2m',
				material: 'GLAZURA',
				brand: 'Cersanit',
				name: 'Marble Viola - 5',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '6cwazv5',
				material: 'GLAZURA',
				brand: 'Cersanit',
				name: 'Marble Viola - 6',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'ir7acij',
				material: 'GLAZURA',
				brand: 'Cersanit',
				name: 'Marble Viola - 7',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'fqqp6f3',
				material: 'MOZAIKA',
				brand: 'Dunin',
				name: 'Mint Breath - 1',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '2lgnt7x',
				material: 'MOZAIKA',
				brand: 'Dunin',
				name: 'Mint Breath - 2',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '1i2qqk6',
				material: 'MOZAIKA',
				brand: 'Dunin',
				name: 'Mint Breath - 3',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'kl5lh5d',
				material: 'MOZAIKA',
				brand: 'Dunin',
				name: 'Mint Breath - 4',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'zkw877r',
				material: 'MOZAIKA',
				brand: 'Dunin',
				name: 'Mint Breath - 5',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '8s1z8zt',
				material: 'MOZAIKA',
				brand: 'Dunin',
				name: 'Mint Breath - 6',
				imageUrl: 'https://via.placeholder.com/150',
			},
		],
	},
	{
		title: 'BLATY',
		items: [
			{
				id: '9tlkdct',
				material: 'MARMUR',
				brand: 'Meusstone',
				name: 'Nazwa kamienia - 1',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'res55gm',
				material: 'MARMUR',
				brand: 'Meusstone',
				name: 'Nazwa kamienia - 2',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'xagf3nb',
				material: 'MARMUR',
				brand: 'Meusstone',
				name: 'Nazwa kamienia - 3',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '504rwyu',
				material: 'MARMUR',
				brand: 'Meusstone',
				name: 'Nazwa kamienia - 4',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '4lrhosf',
				material: 'MARMUR',
				brand: 'Meusstone',
				name: 'Nazwa kamienia - 5',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '3ltikyh',
				material: 'MARMUR',
				brand: 'Meusstone',
				name: 'Nazwa kamienia - 6',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'dfai4d7',
				material: 'MARMUR',
				brand: 'Meusstone',
				name: 'Nazwa kamienia - 7',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'bpsvrz8',
				material: 'MARMUR',
				brand: 'Meusstone',
				name: 'Nazwa kamienia - 8',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'yioso24',
				material: 'MARMUR',
				brand: 'Meusstone',
				name: 'Nazwa kamienia - 9',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '4hcrsvl',
				material: 'MARMUR',
				brand: 'Meusstone',
				name: 'Nazwa kamienia - 10',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '3u8pnt0',
				material: 'KWARCYT NATURALNY',
				brand: 'Krak-stone',
				name: 'Nazwa kamienia - 1',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 't3vl9qj',
				material: 'KWARCYT NATURALNY',
				brand: 'Krak-stone',
				name: 'Nazwa kamienia - 2',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'wzibnxs',
				material: 'KWARCYT NATURALNY',
				brand: 'Krak-stone',
				name: 'Nazwa kamienia - 3',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'osbkg3k',
				material: 'KWARCYT NATURALNY',
				brand: 'Krak-stone',
				name: 'Nazwa kamienia - 4',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '55iua7i',
				material: 'KWARCYT NATURALNY',
				brand: 'Krak-stone',
				name: 'Nazwa kamienia - 5',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'zr65kso',
				material: 'KWARCYT NATURALNY',
				brand: 'Krak-stone',
				name: 'Nazwa kamienia - 6',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'oosl2f4',
				material: 'KWARCYT NATURALNY',
				brand: 'Krak-stone',
				name: 'Nazwa kamienia - 7',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'xlwyx1b',
				material: 'KWARCYT NATURALNY',
				brand: 'Krak-stone',
				name: 'Nazwa kamienia - 8',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'pp800m6',
				material: 'KWARCYT NATURALNY',
				brand: 'Krak-stone',
				name: 'Nazwa kamienia - 9',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'dg45g8k',
				material: 'KWARCYT NATURALNY',
				brand: 'Krak-stone',
				name: 'Nazwa kamienia - 10',
				imageUrl: 'https://via.placeholder.com/150',
			},
		],
	},
	{
		title: 'MEBLE',
		items: [
			{
				id: 'klgvq05',
				material: 'FORNIR',
				brand: 'Atpol',
				name: 'Nazwa kamienia - 1',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'w1udn4m',
				material: 'FORNIR',
				brand: 'Atpol',
				name: 'Nazwa kamienia - 2',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'dcq6j2i',
				material: 'FORNIR',
				brand: 'Atpol',
				name: 'Nazwa kamienia - 3',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'e4ddo5u',
				material: 'FORNIR',
				brand: 'Atpol',
				name: 'Nazwa kamienia - 4',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '6c84f7a',
				material: 'FORNIR',
				brand: 'Atpol',
				name: 'Nazwa kamienia - 5',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'fh3dcm4',
				material: 'FORNIR',
				brand: 'Atpol',
				name: 'Nazwa kamienia - 6',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '38t9tbw',
				material: 'FORNIR',
				brand: 'Atpol',
				name: 'Nazwa kamienia - 7',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '9gkxa6l',
				material: 'LAMINAT',
				brand: 'Egger',
				name: 'Nazwa kamienia - 1',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'dyn9h6g',
				material: 'LAMINAT',
				brand: 'Egger',
				name: 'Nazwa kamienia - 2',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '1rfd012',
				material: 'LAMINAT',
				brand: 'Egger',
				name: 'Nazwa kamienia - 3',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'v94lrqh',
				material: 'LAMINAT',
				brand: 'Egger',
				name: 'Nazwa kamienia - 4',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '5i7z4yt',
				material: 'LAMINAT',
				brand: 'Egger',
				name: 'Nazwa kamienia - 5',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '02f8xqw',
				material: 'LAMINAT',
				brand: 'Egger',
				name: 'Nazwa kamienia - 6',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'p2jle2u',
				material: 'LAMINAT',
				brand: 'Egger',
				name: 'Nazwa kamienia - 7',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'z3kk21j',
				material: 'LAMINAT',
				brand: 'Swiss-krono',
				name: 'Nazwa kamienia - 1',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: '8e94asw',
				material: 'LAMINAT',
				brand: 'Swiss-krono',
				name: 'Nazwa kamienia - 2',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'f8sfbfh',
				material: 'LAMINAT',
				brand: 'Swiss-krono',
				name: 'Nazwa kamienia - 3',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'rknziv2',
				material: 'LAMINAT',
				brand: 'Swiss-krono',
				name: 'Nazwa kamienia - 4',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'jh9zpd6',
				material: 'LAMINAT',
				brand: 'Swiss-krono',
				name: 'Nazwa kamienia - 5',
				imageUrl: 'https://via.placeholder.com/150',
			},
			{
				id: 'wu80f2r',
				material: 'LAMINAT',
				brand: 'Swiss-krono',
				name: 'Nazwa kamienia - 6',
				imageUrl: 'https://via.placeholder.com/150',
			},
		],
	},
];
