import Footer from '@/components/footer/Footer';
import Nav from '@/components/nav/Nav';
import PageTransition from '@/components/PageTransition';
import TextPage from '@/components/TextPage';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ReactNode } from 'react';
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang='pl' className='scroll-smooth'>
			<body
				className={cn(
					`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`,
					`bg-background relative scroll-smooth xl:flex`
					// `[&_*]:outline [&_*]:outline-[1px] [&_*]:outline-pink-400`
				)}
			>
				<Nav />
				{children}
				<Footer />
			</body>
		</html>
	);
}
